#spring:
#  datasource: url=jdbc:postgresql://localhost:5321/
#              username=some-postgres
#              password=mysecretpassword



spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto:  update

    properties:
      hibernate:
        format_sql: true

    show-sql: false

logging:
  level:
    ROOT: ERROR